// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payload_chunk.proto
// Protobuf C++ Version: 6.33.0

#ifndef payload_5fchunk_2eproto_2epb_2eh
#define payload_5fchunk_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_payload_5fchunk_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_payload_5fchunk_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_payload_5fchunk_2eproto;
}  // extern "C"
class NextHint;
struct NextHintDefaultTypeInternal;
extern NextHintDefaultTypeInternal _NextHint_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NextHint_class_data_;
class PayloadChunk;
struct PayloadChunkDefaultTypeInternal;
extern PayloadChunkDefaultTypeInternal _PayloadChunk_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadChunk_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PayloadChunk final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PayloadChunk) */ {
 public:
  inline PayloadChunk() : PayloadChunk(nullptr) {}
  ~PayloadChunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadChunk* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadChunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadChunk(::google::protobuf::internal::ConstantInitialized);

  inline PayloadChunk(const PayloadChunk& from) : PayloadChunk(nullptr, from) {}
  inline PayloadChunk(PayloadChunk&& from) noexcept
      : PayloadChunk(nullptr, ::std::move(from)) {}
  inline PayloadChunk& operator=(const PayloadChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadChunk& operator=(PayloadChunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadChunk& default_instance() {
    return *reinterpret_cast<const PayloadChunk*>(
        &_PayloadChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PayloadChunk& a, PayloadChunk& b) { a.Swap(&b); }
  inline void Swap(PayloadChunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadChunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadChunk* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadChunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadChunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadChunk& from) { PayloadChunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadChunk* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PayloadChunk"; }

  explicit PayloadChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadChunk& from);
  PayloadChunk(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadChunk&& from) noexcept
      : PayloadChunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChunkIdFieldNumber = 1,
    kKeyIdFieldNumber = 2,
  };
  // optional int64 chunk_id = 1;
  bool has_chunk_id() const;
  void clear_chunk_id() ;
  ::int64_t chunk_id() const;
  void set_chunk_id(::int64_t value);

  private:
  ::int64_t _internal_chunk_id() const;
  void _internal_set_chunk_id(::int64_t value);

  public:
  // optional int64 key_id = 2;
  bool has_key_id() const;
  void clear_key_id() ;
  ::int64_t key_id() const;
  void set_key_id(::int64_t value);

  private:
  ::int64_t _internal_key_id() const;
  void _internal_set_key_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:PayloadChunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadChunk& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t chunk_id_;
    ::int64_t key_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payload_5fchunk_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadChunk_class_data_;
// -------------------------------------------------------------------

class NextHint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NextHint) */ {
 public:
  inline NextHint() : NextHint(nullptr) {}
  ~NextHint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NextHint* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NextHint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NextHint(::google::protobuf::internal::ConstantInitialized);

  inline NextHint(const NextHint& from) : NextHint(nullptr, from) {}
  inline NextHint(NextHint&& from) noexcept
      : NextHint(nullptr, ::std::move(from)) {}
  inline NextHint& operator=(const NextHint& from) {
    CopyFrom(from);
    return *this;
  }
  inline NextHint& operator=(NextHint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NextHint& default_instance() {
    return *reinterpret_cast<const NextHint*>(
        &_NextHint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(NextHint& a, NextHint& b) { a.Swap(&b); }
  inline void Swap(NextHint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NextHint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NextHint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NextHint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NextHint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NextHint& from) { NextHint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NextHint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NextHint"; }

  explicit NextHint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NextHint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NextHint& from);
  NextHint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NextHint&& from) noexcept
      : NextHint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChunksInfoFieldNumber = 2,
    kHintMessageFieldNumber = 1,
  };
  // repeated .PayloadChunk chunks_info = 2;
  int chunks_info_size() const;
  private:
  int _internal_chunks_info_size() const;

  public:
  void clear_chunks_info() ;
  ::PayloadChunk* PROTOBUF_NONNULL mutable_chunks_info(int index);
  ::google::protobuf::RepeatedPtrField<::PayloadChunk>* PROTOBUF_NONNULL mutable_chunks_info();

  private:
  const ::google::protobuf::RepeatedPtrField<::PayloadChunk>& _internal_chunks_info() const;
  ::google::protobuf::RepeatedPtrField<::PayloadChunk>* PROTOBUF_NONNULL _internal_mutable_chunks_info();
  public:
  const ::PayloadChunk& chunks_info(int index) const;
  ::PayloadChunk* PROTOBUF_NONNULL add_chunks_info();
  const ::google::protobuf::RepeatedPtrField<::PayloadChunk>& chunks_info() const;
  // optional string hint_message = 1;
  bool has_hint_message() const;
  void clear_hint_message() ;
  const ::std::string& hint_message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hint_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hint_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hint_message();
  void set_allocated_hint_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hint_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hint_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hint_message();

  public:
  // @@protoc_insertion_point(class_scope:NextHint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 29,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NextHint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::PayloadChunk > chunks_info_;
    ::google::protobuf::internal::ArenaStringPtr hint_message_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payload_5fchunk_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NextHint_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PayloadChunk

// optional int64 chunk_id = 1;
inline bool PayloadChunk::has_chunk_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PayloadChunk::clear_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t PayloadChunk::chunk_id() const {
  // @@protoc_insertion_point(field_get:PayloadChunk.chunk_id)
  return _internal_chunk_id();
}
inline void PayloadChunk::set_chunk_id(::int64_t value) {
  _internal_set_chunk_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:PayloadChunk.chunk_id)
}
inline ::int64_t PayloadChunk::_internal_chunk_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_id_;
}
inline void PayloadChunk::_internal_set_chunk_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_id_ = value;
}

// optional int64 key_id = 2;
inline bool PayloadChunk::has_key_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PayloadChunk::clear_key_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t PayloadChunk::key_id() const {
  // @@protoc_insertion_point(field_get:PayloadChunk.key_id)
  return _internal_key_id();
}
inline void PayloadChunk::set_key_id(::int64_t value) {
  _internal_set_key_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:PayloadChunk.key_id)
}
inline ::int64_t PayloadChunk::_internal_key_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_id_;
}
inline void PayloadChunk::_internal_set_key_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_id_ = value;
}

// -------------------------------------------------------------------

// NextHint

// optional string hint_message = 1;
inline bool NextHint::has_hint_message() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void NextHint::clear_hint_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hint_message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& NextHint::hint_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NextHint.hint_message)
  return _internal_hint_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NextHint::set_hint_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.hint_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NextHint.hint_message)
}
inline ::std::string* PROTOBUF_NONNULL NextHint::mutable_hint_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_hint_message();
  // @@protoc_insertion_point(field_mutable:NextHint.hint_message)
  return _s;
}
inline const ::std::string& NextHint::_internal_hint_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hint_message_.Get();
}
inline void NextHint::_internal_set_hint_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hint_message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NextHint::_internal_mutable_hint_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hint_message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NextHint::release_hint_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NextHint.hint_message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.hint_message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hint_message_.Set("", GetArena());
  }
  return released;
}
inline void NextHint::set_allocated_hint_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.hint_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hint_message_.IsDefault()) {
    _impl_.hint_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NextHint.hint_message)
}

// repeated .PayloadChunk chunks_info = 2;
inline int NextHint::_internal_chunks_info_size() const {
  return _internal_chunks_info().size();
}
inline int NextHint::chunks_info_size() const {
  return _internal_chunks_info_size();
}
inline void NextHint::clear_chunks_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunks_info_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::PayloadChunk* PROTOBUF_NONNULL NextHint::mutable_chunks_info(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:NextHint.chunks_info)
  return _internal_mutable_chunks_info()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PayloadChunk>* PROTOBUF_NONNULL NextHint::mutable_chunks_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:NextHint.chunks_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_chunks_info();
}
inline const ::PayloadChunk& NextHint::chunks_info(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NextHint.chunks_info)
  return _internal_chunks_info().Get(index);
}
inline ::PayloadChunk* PROTOBUF_NONNULL NextHint::add_chunks_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::PayloadChunk* _add =
      _internal_mutable_chunks_info()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:NextHint.chunks_info)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PayloadChunk>& NextHint::chunks_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:NextHint.chunks_info)
  return _internal_chunks_info();
}
inline const ::google::protobuf::RepeatedPtrField<::PayloadChunk>&
NextHint::_internal_chunks_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunks_info_;
}
inline ::google::protobuf::RepeatedPtrField<::PayloadChunk>* PROTOBUF_NONNULL
NextHint::_internal_mutable_chunks_info() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.chunks_info_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // payload_5fchunk_2eproto_2epb_2eh
